// list.js
const listings = [
  {
    "id": 1753385117220,
    "category": "Agriculture, fishing, forestry",
    "title": "Area Coordinator",
    "position": "Area Coordinator",
    "placeOfWork": "Kijani Forestry",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-23",
    "deadline": "2025-07-29",
    "jobSummary": "Responsibilities\nPlanning and Supervision; Develops and implements work plans for field activities, ensuring alignment with company objectives. Supervises and manages field operations, including transportation, resource allocation, and other logistics. Coordinate with Branch Coordinators to ensure timely execution of nursery and tree planting activities. Conduct regular field visits to monitor progress, address challenges, and ensure adherence to standards.\nBudgeting and Resource Management; Prepare budgets for field operations, ensuring efficient allocation of resources, monitor expenditures to ensure cost-effectiveness and accountability, prepare resource requisitions and oversee distribution to Branch and Parish Coordinators, conduct regular stock-taking exercises to ensure accurate inventory records.\n\nTechnical Support; Provides expert advice on forestry practices, nursery management, and tree planting techniques. Troubleshoot technical issues and support Branch Coordinators and parish coordinators in resolving operational challenges. Facilitate capacity-building initiatives for field staff to enhance their technical expertise.\n\nDocumentation, Accountability and Reporting; Oversee the collection, validation, and verification of data submitted by Branch and Parish Coordinators to ensure accuracy and reliability. Use the data for making decisions. Maintain comprehensive, organized records of all field activities, budgets, inventories, and research findings. Prepare and submit detailed reports to the Manager, Plantation Development/Regional Manager, including progress updates, identified challenges, and actionable recommendations. Utilize digital tools and applications to streamline data management and reporting processes, ensuring timely and efficient communication.\n\nTeam Management and Leadership; Lead and manage a team of Branch and Parish Coordinators, fostering a culture of accountability and high performance, conduct regular performance evaluations, providing feedback and guidance for improvement, organize team-building activities and promote a positive working environment, facilitate workshops, meetings, and planning sessions including other support teams to foster a culture of collaboration.\n\nCompliance Enforcement: Ensure all team members adhere to company standards, policies, processes, and systems. Conduct regular audits to identify and address non-compliance issues. Provide training and support to team members to improve adherence to company protocols.\n\nStakeholder Engagement; Coordinate with district agencies, local leaders, media, private sector entities, and other stakeholders for seamless operations and knowledge-sharing. Organize collaborative meetings with local leaders and farmer groups for experience-sharing, Act as the main liaison between Kijani Forestry and local authorities, ensuring alignment with community needs.\n\nInternship Program: Collaborate with the other field teams to ensure candidates are interviewed appropriately. Ensure that PC-Trainees receive the training and support needed to build expertise in kijani forestry practices. Oversee and evaluate their performance in the field.\n\nMonitoring and Reporting; Conduct regular field visits to monitor operations, resolve issues, and provide necessary referrals. Maintain thorough records of activities, budgets. Prepare and submit detailed reports on area-level activities, progress, and challenges to the Manager, Plantation Development.\n\nHealth, Safety, and Environmental Compliance: Ensure compliance with health and safety regulations during all field activities, including the use of protective gear. Promote sustainable practices, emphasizing waste management to promote soil conservation, water management, and biodiversity protection. Conduct regular assessments with the farmers and staff to confirm adherence to environmental standards and regulatory requirements.\n\nOther tasks as assigned by management\n\n\nQualifications;\n\nA bachelor's degree in forestry, Agriculture, Environmental Management, Business Administration, or a related field is required.\nAbility to ride a motorcycle is an added advantage.",
    "description": "123",
    "contact": "+256393255297",
    "address": "Uganda, Gulu",
    "url": "https://www.kijaniforestry.com/"
  },
  {
    "id": 1753386192902,
    "category": "Healthcare",
    "title": "Hospital Process Manager (Trainee)",
    "position": "Hospital Process Manager (Trainee)",
    "placeOfWork": "Gulu Independent Hospital",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-24",
    "deadline": "2025-08-01",
    "jobSummary": "Gulu Independent Hospital is a private healthcare facility in Gulu, Uganda. It was established to provide quality, affordable, and accessible healthcare services to the community. The hospital offers a range of medical services, including general consultations, specialized treatments, laboratory services, and maternal and child health care. It aims to be a leading provider of healthcare in the region, focusing on patient-centered care and community well-being\n\nRequirements: BSc in Accounting Or Business (MBA completed is a bonus)\nSend your CV and cover letter explaining why you are suitable for the position you are applying for to ivfteam@kihug.com",
    "description": null,
    "contact": "ivfteam@kihug.com",
    "address": "Uganda, Gulu",
    "url": null
  },
  {
    "id": 1753386483286,
    "category": "Healthcare",
    "title": "Executive Assistant",
    "position": "Executive Assistant",
    "placeOfWork": "Gulu Independent Hospital",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-24",
    "deadline": "2025-08-01",
    "jobSummary": "Gulu Independent Hospital is a private healthcare facility in Gulu, Uganda. It was established to provide quality, affordable, and accessible healthcare services to the community. The hospital offers a range of medical services, including general consultations, specialized treatments, laboratory services, and maternal and child health care. It aims to be a leading provider of healthcare in the region, focusing on patient-centered care and community well-being\n\n\nWork under direct instructions of Managing Director\nRequirements: BSc, strong communication skills, and good interpersonal skills.\n\nMethod of Application\nSend your CV and cover letter explaining why you are suitable for the position you are applying for to ivfteam@kihug.com",
    "description": null,
    "contact": "ivfteam@kihug.com",
    "address": "Uganda, Gulu",
    "url": null
  },
  {
    "id": 1753386701917,
    "category": "Healthcare",
    "title": "Medical Record Officer",
    "position": "Medical Record Officer",
    "placeOfWork": "Gulu Independence Hospital",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-24",
    "deadline": "2025-08-01",
    "jobSummary": "Gulu Independent Hospital is a private healthcare facility in Gulu, Uganda. It was established to provide quality, affordable, and accessible healthcare services to the community. The hospital offers a range of medical services, including general consultations, specialized treatments, laboratory services, and maternal and child health care. It aims to be a leading provider of healthcare in the region, focusing on patient-centered care and community well-being\n\n\nRequirements: BSc in Quantitative Studies preferred;\nAccounting Degree holders are also accepted. Must be a quick learner. \nExperience dealing with medical insurances and billing is a plus.\n\nMethod of Application\nSend your CV and cover letter explaining why you are suitable for the position you are applying for to ivfteam@kihug.com",
    "description": null,
    "contact": "ivfteam@kihug.com",
    "address": "Uganda, Gulu",
    "url": null
  },
  {
    "id": 1753386913914,
    "category": "HealthCare",
    "title": "Patients Coordinator",
    "position": "Patients Coordinator",
    "placeOfWork": "Gulu Independence Hospital",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-24",
    "deadline": "2025-08-01",
    "jobSummary": "Gulu Independent Hospital is a private healthcare facility in Gulu, Uganda. It was established to provide quality, affordable, and accessible healthcare services to the community. The hospital offers a range of medical services, including general consultations, specialized treatments, laboratory services, and maternal and child health care. It aims to be a leading provider of healthcare in the region, focusing on patient-centered care and community well-being\n\n\nRole involves front desk reception and liaising with patients and medical staff. \nStrong communication skills and customer service skills required.\n\nMethod of Application\nSend your CV and cover letter explaining why you are suitable for the position you are applying for to ivfteam@kihug.com",
    "description": null,
    "contact": "ivfteam@kihug.com",
    "address": "Uganda, Gulu",
    "url": null
  },
  {
    "id": 1753387092782,
    "category": "healthcare",
    "title": "Cleaning Supervisor",
    "position": "Cleaning Supervisor",
    "placeOfWork": "Gulu Independent Hospital",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-24",
    "deadline": "2025-08-01",
    "jobSummary": "Gulu Independent Hospital is a private healthcare facility in Gulu, Uganda. It was established to provide quality, affordable, and accessible healthcare services to the community. The hospital offers a range of medical services, including general consultations, specialized treatments, laboratory services, and maternal and child health care. It aims to be a leading provider of healthcare in the region, focusing on patient-centered care and community well-being\n\n\nRequirements: Strong communication skills and ability to lead cleaning team and deliver high standard of cleanliness.\n\nMethod of Application\nSend your CV and cover letter explaining why you are suitable for the position you are applying for to ivfteam@kihug.com",
    "description": null,
    "contact": "ivfteam@kihug.com",
    "address": "Uganda, Gulu",
    "url": null
  },
  {
    "id": 1753387264111,
    "category": "healthcare",
    "title": "Regional Patient Representative",
    "position": "Regional Patient Representative",
    "placeOfWork": "Gulu Independent Hospital",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-24",
    "deadline": "2025-08-01",
    "jobSummary": "Gulu Independent Hospital is a private healthcare facility in Gulu, Uganda. It was established to provide quality, affordable, and accessible healthcare services to the community. The hospital offers a range of medical services, including general consultations, specialized treatments, laboratory services, and maternal and child health care. It aims to be a leading provider of healthcare in the region, focusing on patient-centered care and community well-being\n\n\nRequirements: Must speak some of local languages from bordering countries. Communicate effectively with patients and assist in outreach.\n\nMethod of Application\nSend your CV and cover letter explaining why you are suitable for the position you are applying for to ivfteam@kihug.com",
    "description": null,
    "contact": "ivfteam@kihug.com",
    "address": "Uganda, Gulu",
    "url": null
  },
  {
    "id": 1753387454748,
    "category": "healthcare",
    "title": "IT Support Officer",
    "position": "IT Support Officer",
    "placeOfWork": "Gulu Independent Hospital",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-24",
    "deadline": "2025-08-01",
    "jobSummary": "Gulu Independent Hospital is a private healthcare facility in Gulu, Uganda. It was established to provide quality, affordable, and accessible healthcare services to the community. The hospital offers a range of medical services, including general consultations, specialized treatments, laboratory services, and maternal and child health care. It aims to be a leading provider of healthcare in the region, focusing on patient-centered care and community well-being\n\n\nRequirements: Relevant IT qualifications and experience in support roles.\n\nMethod of Application\nSend your CV and cover letter explaining why you are suitable for the position you are applying for to ivfteam@kihug.com",
    "description": null,
    "contact": "ivfteam@kihug.com",
    "address": "Uganda, Gulu",
    "url": null
  },
  {
    "id": 1753387616959,
    "category": "healthcare",
    "title": "Nurse Coordinator",
    "position": "Nurse Coordinator",
    "placeOfWork": "Gulu Independent Hospital",
    "location": "Gulu Uganda",
    "datePosted": "2025-07-24",
    "deadline": "2025-08-24",
    "jobSummary": "Gulu Independent Hospital is a private healthcare facility in Gulu, Uganda. It was established to provide quality, affordable, and accessible healthcare services to the community. The hospital offers a range of medical services, including general consultations, specialized treatments, laboratory services, and maternal and child health care. It aims to be a leading provider of healthcare in the region, focusing on patient-centered care and community well-being\n\n\nRequirements: Diploma or Degree in Nursing with supervising experience.\n\nMethod of Application\nSend your CV and cover letter explaining why you are suitable for the position you are applying for to ivfteam@kihug.com",
    "description": null,
    "contact": "ivfteam@kihug.com",
    "address": "Uganda, Gulu",
    "url": null
  }
];
